# This is a simple workflow that is manually triggered

name: Test script run workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job 
  script-run-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks out repo
    - name: Checkout
      uses: actions/checkout@v1
    # Runs a simple script which creates a text file
    - name: Run script
      run: ./simpleArtifact/testrun.sh
      shell: bash
    # Uploads the output file as an artifact
    - name: Upload output file
      uses: actions/upload-artifact@v1
      with:
         name: output-text-file
         path: output.txt
